import { NowPlaying } from "@/components/audio/now-playing";
import { MusicProvider } from "@/components/providers/music-provider";
import { Header } from "@/components/ui/header";
import { getSession } from "@/lib/auth";
import axios from "axios";
import { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Layout({ children }: Readonly<{ children: React.ReactNode; }>) {

    const session = await getSession()
    const token = session?.access_token


    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                
                <MusicProvider>
                    <div className='flex flex-col h-screen'>
                        <Header/>
                        <div className='overflow-hidden flex h-full'>
                            <div className='hidden md:inline overflow-hidden flex-auto w-[35%] bg-zinc-100 dark:bg-zinc-900 rounded-[25px] ml-2 mr-1 mb-2 '>
                                    {children}
                            </div>
                            <div className=' flex-1 bg-zinc-100 dark:bg-zinc-900 rounded-[25px] mr-2 ml-2 md:ml-1 mt-2 md:mt-0 mb-2 border-2'>
                                {token ? <NowPlaying access_token={token}/> : <div className='flex h-full items-center justify-center font-bold'>Log in to use player</div>}
                            </div>   
                        </div> 
                    </div>
                </MusicProvider>
            </body>
        </html>
    );
}

//